name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: npm install
      run: |
        npm ci
    - name: npm build
      run: |
        npm run build
      env:
        CI: true
